sonar.projectKey=jobhunt-os
sonar.projectName=jobhunt-os
sonar.sourceEncoding=UTF-8
sonar.sources=cmd,internal,web,migrations,docs
sonar.tests=internal
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage/coverage.out
sonar.exclusions=fixtures/**
sonar.qualitygate.wait=true
